name       : python-acme
version    : 0.38.0
release    : 16
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-0.38.0.tar.gz : 1c1e9c0826a8f72d670b0ca28b7e6392ce4781eb33222f35133705b6551885d8
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
