name       : python-acme
version    : 0.29.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/a/acme/acme-0.29.1.tar.gz : a2e203ade83cd1eaf19112004a63073830211cf7759d437f634babb08c49b47c
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
