name       : python-acme
version    : 0.24.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/a/acme/acme-0.24.0.tar.gz : d655e0627c0830114ab3f6732d8bf2f4a2c36f602e0cde10988684e229b501cb
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-ndg-httpsclient
    - python-openssl
    - python-pyrfc3339
    - python-pytz
    - python-requests
    - python-setuptools
rundeps    :
    - python-josepy
    - python-mock
    - python-openssl
    - python-pyrfc3339
    - python-pytz
    - python-requests
    - python-setuptools
    - python-six
    - python-werkzeug
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd
