name       : python-acme
version    : 0.37.2
release    : 15
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-0.37.2.tar.gz : 88798fae3bc692397db79c66930bd02fcaba8a6b1fba9a62f111dda42cc47f5c
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
