name       : python-acme
version    : 0.36.0
release    : 14
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-0.36.0.tar.gz : 0461ee3c882d865e98e624561843dc135fa1a1412b15603d7ebfbb392de6a668
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
