name       : python-acme
version    : 0.18.2
release    : 1
source     :
    - https://pypi.python.org/packages/87/25/83cd8cf0ee345b406adaa920022973bbd473001ce7272e99e86bcb567859/acme-0.18.2.tar.gz : 718efa9b3a7e6defcc7179e214a838d43a2bcef7dbd77667a2e505504e453ef6
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-setuptools
rundeps    :
    - python-mock
    - python-openssl
    - python-pyrfc3339
    - python-pytz
    - python-requests
    - python-setuptools
    - python-six
    - python-werkzeug
build      : |
    %python_setup
install    : |
    %python_install

