name       : python-acme
version    : 0.27.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/a/acme/acme-0.27.0.tar.gz : e6158df21b887c24ab4a39d16ac6a8c644d543079ebefd580966e563be4102f3
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-ndg-httpsclient
    - python-openssl
    - python-pyrfc3339
    - python-pytest
    - python-pytz
    - python-requests-toolbelt
    - python-setuptools
rundeps    :
    - python-josepy
    - python-mock
    - python-openssl
    - python-pyrfc3339
    - python-pytz
    - python-requests-toolbelt
    - python-setuptools
    - python-six
    - python-werkzeug
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test
    popd
