name       : python-acme
version    : 0.27.1
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/a/acme/acme-0.27.1.tar.gz : 31a7b9023ce183616e6ebd5d783e842c3d68696ff70db59a06db9feea8f54f90
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-ndg-httpsclient
    - python-openssl
    - python-pyrfc3339
    - python-pytest
    - python-pytz
    - python-requests-toolbelt
    - python-setuptools
rundeps    :
    - python-josepy
    - python-mock
    - python-openssl
    - python-pyrfc3339
    - python-pytz
    - python-requests-toolbelt
    - python-setuptools
    - python-six
    - python-werkzeug
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_test
