name       : python-acme
version    : 1.7.0
release    : 20
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-1.7.0.tar.gz : 288d9bbb075278961d224e43f7f386c491d25366a98ed89a62771c5022978386
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test
