name       : python-acme
version    : 1.4.0
release    : 19
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-1.4.0.tar.gz : f12cb59762e0b833911b87e95cb16e85a162517ba4aa3440594bdf3b8126fc69
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test
