name       : python-acme
version    : 1.0.0
release    : 18
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-1.0.0.tar.gz : 6a08f12f848ce563b50bca421ba9db653df9f82cfefeaf8aba517f046d1386c2
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test
