name       : python-acme
version    : 0.33.1
release    : 12
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-0.33.1.tar.gz : b38cdb71d0071efe1f1190a744f8f95f3c698b76ac0f5d919bbfe3522e277a82
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
