name       : python-acme
version    : 0.19.0
release    : 2
source     :
    - https://pypi.python.org/packages/a8/4e/6682c3192f9216f5eac3993e3de24b4bd28f371b28f0ea6a8034b0f1529b/acme-0.19.0.tar.gz : 1fa23d64d494aaf001e6fe857c461fcfff10f75a1c2c35ec831447f641e1e822
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-cryptography
    - python-ipaddress
    - python-mock
    - python-ndg-httpsclient
    - python-nose
    - python-openssl
    - python-pyrfc3339
    - python-pytz
    - python-requests
    - python-setuptools
rundeps    :
    - python-mock
    - python-openssl
    - python-pyrfc3339
    - python-pytz
    - python-requests
    - python-setuptools
    - python-six
    - python-werkzeug
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_setup nosetests

