name       : python-acme
version    : 0.30.0
release    : 10
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-0.30.0.tar.gz : 984b6d00bec73dcfa616636a760e80ca14bd246fb908710a656547f542f09445
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-pytest
    - python-requests-toolbelt
rundeps    :
    - python-josepy
    - python-mock
    - python-pyrfc3339
    - python-requests-toolbelt
    - python-six
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
